export const SIGNUP = 'SIGNUP'
export const SIGNUP_PROCEED = 'SIGNUP_PROCEED'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_PROCEED = 'SIGNIN_PROCEED'
export const SIGNIN_ERROR = 'SIGNIN_ERROR'

export const SIGNOUT = 'SIGNOUT'

export const GET_CUSTOMER_PROCEED = 'GET_CUSTOMER_PROCEED'
export const SAVE_USER_DATA = 'SAVE_USER_DATA'

export const TOOGLE_PROFILE_EDIT = 'TOOGLE_PROFILE_EDIT'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_PROCEED = 'UPDATE_PROCEED'
export const UPDATE_ERROR = 'UPDATE_ERROR'

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_PROCEED = 'CHANGE_PASSWORD_PROCEED'
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'
