export const TEST_STORE = 'TEST_STORE'
export const MODAL_TOGGLE = 'MODAL_TOGGLE'
export const MODAL_CLOSE = 'MODAL_CLOSE'
export const MODAL_OPEN = 'MODAL_OPEN'
export const FILTERS_GET_DATA = 'FILTERS_GET_DATA'
