export const MODAL_TOGGLE = 'MODAL_TOGGLE'
export const MODAL_CLOSE = 'MODAL_CLOSE'
export const MODAL_OPEN = 'MODAL_OPEN'
export const FILTERS_SET_PARSED_FILTERS_PARAMS =
  'FILTERS_SET_PARSED_FILTERS_PARAMS'
