export const ADD_SERVER_ERROR = 'ADD_SERVER_ERROR'
export const CLEAR_SERVER_ERRORS = 'CLEAR_SERVER_ERRORS'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const CLEAR_NOTIFICATIONS = 'CLEAR_CLEAR_NOTIFICATIONS'
export const CLEAR_ALL = 'CLEAR_ALL'

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'
